include(CheckCXXSourceCompiles)

function(infeng_check_intrinsic RESULT FLAG)
  set(old_flags "${CMAKE_REQUIRED_FLAGS}")
  set(CMAKE_REQUIRED_FLAGS "${old_flags} ${FLAG}")
  check_cxx_source_compiles("#include <immintrin.h>\nint main(){return 0;}" ${RESULT})
  set(${RESULT} "${${RESULT}}" PARENT_SCOPE)
  set(CMAKE_REQUIRED_FLAGS "${old_flags}")
endfunction()

function(infeng_generate_cpu_header OUTPUT_PATH)
  set(options)
  set(oneValueArgs)
  set(multiValueArgs)
  cmake_parse_arguments(PARSE_ARGV 1 "" "" "" "")

  set(has_avx2 0)
  set(has_avx512 0)
  set(has_amx 0)

  if(INFENG_AVX2)
    infeng_check_intrinsic(HAS_TMP "-mavx2")
    if(HAS_TMP)
      set(has_avx2 1)
    endif()
  endif()

  if(INFENG_AVX512)
    infeng_check_intrinsic(HAS_TMP "-mavx512f -mavx512bw -mavx512vl -mavx512dq")
    if(HAS_TMP)
      set(has_avx512 1)
    endif()
  endif()

  if(INFENG_AMX)
    infeng_check_intrinsic(HAS_TMP "-mamx-int8 -mamx-bf16 -mavx512f")
    if(HAS_TMP)
      set(has_amx 1)
    endif()
  endif()

  file(WRITE ${OUTPUT_PATH} "#pragma once\n")
  file(APPEND ${OUTPUT_PATH} "#define INFENG_HAS_AVX2 ${has_avx2}\n")
  file(APPEND ${OUTPUT_PATH} "#define INFENG_HAS_AVX512 ${has_avx512}\n")
  file(APPEND ${OUTPUT_PATH} "#define INFENG_HAS_AMX ${has_amx}\n")
endfunction()
